### PR TITLE
Style Pass

### PR DESCRIPTION
**Pull request by Sean-Oh**
### Homepage doesn't scale properly on larger displays
screen shot 2017-09-07 at 4 26 14 pm
### Lack of proper mobile navigation clutters the screen
screen shot 2017-09-07 at 4 26 52 pm
### Larger displays
screen shot 2017-09-07 at 4 57 46 pm
### Mobile Experience
- Page navigation elements (eg Product design, brand design, etc.) are stuffed inside a hamburger menu 
- Navigation elements within a page (eg Components within product design) are placed inside a sub-menu 

gif

## Notes
- I changed the navigation BEM since there were some inconsistencies in the syntax.
- I'm not sure if the `onClick / onBlur` handlers I introduced are the most optimal way to accomplish adding / removing `classNames`. It works for now, but maybe there's a better way to accomplish this.

### CODE REVIEW

**Comment by Sean-Oh** [comment]
# More Edits based on recent designs
## Desktop
### General
* Active link styles
* Grey BG
* No more `welcome` link
* Sidebar navigation styles
screen shot 2017-10-02 at 9 09 34 pm
### Syntax highlighting
* Added [prismjs](http://prismjs.com/) to `package.json`
* Created `Code` react component for code snippets /w syntax highlighting (can pass text and language props)
* Replaced code snippets on each relevant page within the `UI Design` directory
screen shot 2017-10-02 at 9 06 57 pm
### On Scroll
* Header has opacity
* Sidebar isn't fixed anymore
screen shot 2017-10-02 at 9 07 01 pm

## Mobile
### Home Screen
- No BG image, sizing, etc.
screen shot 2017-10-02 at 9 22 25 pm
### Hamburger Menu
* Full Screen
* Green hamburger menu focus
screen shot 2017-10-02 at 9 22 30 pm

**Comment by marcgurney** [comment]
😍 this is looking really good!

**Comment by marcgurney** [comment]
Will take a closer look tomorrow, but a few things I noticed:

* Code blocks via the `code` component you created is a _huge_ improvement but we should be careful to still strip out utility classes from the sample markup.
* Hamburger links don't seem to go anywhere yet
* The mobile breakpoints seem to also affect the example components, not sure the best approach for avoiding this (see screenshot)

screen shot 2017-10-02 at 9 53 14 pm

This is really awesome. Will look again tomorrow and maybe we can just merge it in and continue future work in a different branch.

**Comment by Sean-Oh** [comment]
Rebased off master.

**Pull request merged**
